"use client";
import Header from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import MainProvider from "@/components/context/MainProvider";

// const Header = dynamic(() => import("@/components/header"), {
//   ssr: false,
// });

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MainProvider>
        <div className="p-[40px]">
          <body className={inter.className}>
            <Header />
            {children}
            <div className="footer">Footer</div>
          </body>
        </div>
      </MainProvider>
    </html>
  );
}
